### ISSUE TITLE
dejavu and time variables not defined

### ISSUE THREAD

**Issue by BlazeIsClone** [booleans-oss/DiscordModMail#1]
I tried to get your code working but I seem to fail I get two variables undefined 
**dejavu** and **time** variables.

file: `\events\modmail\modmaildm.js`

**Comment by booleans-oss** [comment]
Thank you for the issue. I forget about those variables, my bad.

I have fixed them by adding them to the Client Instance which means that these variables will be init each time you re-launch your bot. To avoid this behavior, the only solution is to use a database but I want this project to remain as simple as possible.
